<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
<!--Google Font - Atkinson Hyperlegible-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
<!--CSS-->
    <link rel="stylesheet" href="https://meyerweb.com/eric/tools/css/reset/reset.css" type="text/css" >
    <link rel="stylesheet" href="css/style.css" type="text/css" >


    
    <title><?= $title?></title>
</head>
<body>
    <div id="app-container">
        
        <header>
        <nav class="">
        <?php if(isset($_SESSION['user'])): ?>
            <details>
                <summary><?= $_SESSION['user']->getUsername() ?></summary>
                <menu>
                    <li class="">
                        <a href="./sign-out">Se déconnecter</a>
                    </li>
                    <li class="">
                        <a href="./profil">Profil</a>
                    </li>
                    <li class="">
                        <a href="./my-routes">Mes routes</a>
                    </li>
                </menu>
            </details>
        <?php else: ?>    
            <details>
                <summary>Invité</summary>
                <menu>
                    <li class="">
                        <a href="./sign-up">Inscription</a>
                    </li>
                    <li class="">
                        <a href="./sign-in">Connection</a>
                    </li>
                </menu>
            </details>
        <?php endif;?>
            
                <a href='./'>
                    <img src="#" alt="logo">
                    <h1>enRoute</h1>
                </a>
            
        </nav>
    </header>
        
        <?= $viewContent?>
        
    </div>
    
</body>
</html>