<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
<!--Google Font - Atkinson Hyperlegible-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
<!--CSS-->
    <link rel="stylesheet" href="https://meyerweb.com/eric/tools/css/reset/reset.css" type="text/css" >
    <link rel="stylesheet" href="css/style.css" type="text/css" >

<!--leaf-->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin="">
<!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
    
<!--Script-->
    <script defer src="script/ListPoint.js"></script>
    
    <script defer src="script/searchbar.js"></script>
    
    <script defer src="script/script.js"></script>
    <!--<script defer type="text/javascript" src="script/map.js"></script>-->
    
    <title><?= $title?></title>
</head>
<body>
    <header>
        <nav class="">
        <?php if(isset($_SESSION['user'])): ?>
            <details>
                <summary><?= $_SESSION['user']->getUsername() ?></summary>
                <menu>
                    <li class="">
                        <a href="./sign-out">Se déconnecter</a>
                    </li>
                    <li class="">
                        <a href="./profil">Profil</a>
                    </li>
                    <li class="">
                        <a href="./my-routes">Mes routes</a>
                    </li>
                </menu>
            </details>
        <?php else: ?>    
            <details>
                <summary>Invité</summary>
                <menu>
                    <li class="">
                        <a href="./sign-up">Inscription</a>
                    </li>
                    <li class="">
                        <a href="./sign-in">Connection</a>
                    </li>
                </menu>
            </details>
        <?php endif;?>
            
                <a href='./'>
                    <img src="#" alt="logo">
                    <h1>enRoute</h1>
                </a>
            
        </nav>
    </header>
    
    <main>
        <?= $viewContent?>
    </main>
    
    <footer></footer>
    
</body>
</html>