<!--Script-->		
<script type="module" src="./script/home.js"></script>

<?php
	include 'elements/search-bar.phtml';
	include 'elements/map.phtml';
	include 'elements/list-point.phtml';
?>

<dialog id="modal_save_route" class="bgcolor-green">

		<span 
			class="cross" 
			title="Fermer" 
			onclick='document.querySelector("#modal_save_route").close();'
			>
			<i class="fa-solid fa-circle-xmark"></i>
		</span>

		<form  id="form_save_route"
			class="modal-content "
			method="post" action="./routes-process"
			>
			
			<fieldset class="bgcolor-blue">
				<legend class="bgcolor-red">Route</legend>
				<input id="save_listpoint" type="hidden" name="listpoint" value="">
				<input id="save_listname" 
					class="bgcolor-white form-input" 
					placeholder="Nommer cette route"
					type="text" 
					name="name" 
					required
					>
			</fieldset>
			
			<button type='button' class='remove bgcolor-yellow hover-green' title="Valider">
				<span>Valider</span><i class="fa-solid fa-circle-check"></i>
			</button>	
		</form>
 
</dialog>

