
<!-- Leaflet Script -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
		 integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
		 crossorigin=""></script>
		
<!--Script-->
		<script type="module" src="./script/module/Position.js"></script>
		<script type="module" src="./script/module/ListPoint.js"></script>
		<script type="module" src="./script/module/SearchBar.js"></script>
		
		<script type="module" src="./script/home.js"></script>


<div id="searchbar" class="bgcolor-gray border-none">
	
	<span id="searchbar_input" class="bgcolor-white border-none">
		<span id="search_glass">
			<i class="fa-solid fa-magnifying-glass"></i>
		</span>
		<input id="search_input" class="form-input"type="text" name="search_adress" placeholder="recherche addresse">
		<span id="search_cross">
			<i class="fa-regular fa-circle-xmark"></i>
		</span> 
	</span>
	<ul id="searchbar_results"></ul>
</div>
<div id="map" class="bgcolor-yellow"></div>
<div id="listpoint" class="bgcolor-green border-none">

		<!--<div class="resize-hitbox"></div>-->

		<div id="list_position" class="bgcolor-yellow">
				<i class="fa-solid fa-location-crosshairs"></i>
				<span>Votre position</span>
		</div>
		
		<div id="list_invite" class="info">
				<p class="icon"><i class="fa-solid fa-map-location-dot"></i></p>
				<p class="label text-center-xs">
						Rechercher quelques adresses.<br>Ajoutez-les, organisez-les ...<br>
						<?php if(isset($_SESSION['user'])==false): ?>
						Créer un compte pour garder<br>et partager cette route.
						<?php endif; ?>
				</p>
		</div>
		
		<!--list of point-->
		<ul class="container"></ul>
		
		<!--template of point-->
		<template> 
				<li class="">
						<div class="up"><i class="fa-solid fa-angles-up"></i></div>
						<div class="label-box bgcolor-blue">
								<span class='label'></span>
								<span class="remove">
										<i class="fa-solid fa-circle-xmark"></i>
								</span>
						</div>
						<div class="down"><i class="fa-solid fa-angles-down"></i></div>
				</li>
		</template>

		<div id="list_total" class="bgcolor-red
		">
				<span><i class="fa-solid fa-map-location-dot"></i><span class='label'></span></span>
		
		<!--display save button if user connected-->
		<?php if(isset($_SESSION['user'])): ?>
				<form id="save_form" method="post" action="./routes-process"> 
						<input id="save_listpoint" type="hidden" name="listpoint" value="">
						<input id="save_listname" type="hidden" name="name" value=''>
						<button id="save_button" type="button" class="bgcolor-yellow hover-green" >
							Sauver <i class="fa-solid fa-download"></i>
						</button>
				</form>
		<?php endif; ?>
		</div>

</div>

<dialog id="modal" class="modal">
	
		<div  class="modal-content">
				<span class="cross">
						<i class="fa-solid fa-circle-xmark"></i>
				</span>
				
				<fieldset>
						<legend>Route</legend>
						<input type="text" name="name" placeholder="Nommer cette route">
				</fieldset>
				
				<button><span>Valider</span><i class="fa-solid fa-circle-check"></i></button>
		</div>
 
</dialog>


<script src="script/map.js"></script>

