
<!-- Leaflet Script -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
    
<!--Script-->
    <script type="module" src="./script/module/Position.js"></script>
    <script type="module" src="./script/module/ListPoint.js"></script>
    <script type="module" src="./script/module/SearchBar.js"></script>
    
    <script type="module" src="./script/home.js"></script>


<div id="searchbar" class="searchbar">
    <span>
        <input class="searchbar-input" type="text" name="search_adress" placeholder="recherche addresse">
        <span><i class="fa-regular fa-circle-xmark"></i></span> 
    </span>
    <ul class="searchbar-results"></ul>
</div>

<div id="listpoint">

    <!--<div class="resize-hitbox"></div>-->

    <div class="position">
        <span><i class="fa-solid fa-location-crosshairs"></i> Votre position</span>
    </div>
    
    <div class="info">
        <p class="icon"><i class="fa-solid fa-map-location-dot"></i></p>
        <p class="label">
            Rechercher quelques adresses.<br>Ajoutez-les, organisez-les ...<br>
            <?php if(isset($_SESSION['user'])==false): ?>
            Créer un compte pour garder<br>et partager cette route.
            <?php endif; ?>
        </p>
    </div>
    
    <!--list of point-->
    <ul></ul>
    
    <!--template of point-->
    <template> 
        <li class="point">
            <div class="up"><i class="fa-solid fa-angles-up"></i></div>
            <div class="label-box">
                <span class='label'></span>
                <span class="remove">
                    <i class="fa-solid fa-circle-xmark"></i>
                </span>
            </div>
            <div class="down"><i class="fa-solid fa-angles-down"></i></div>
        </li>
    </template>

    <div class="total">
        <span><i class="fa-solid fa-map-location-dot"></i><span class='label'></span></span>
    
    <!--display save button if user connected-->
    <?php if(isset($_SESSION['user'])): ?>
        <form method="post" action="./routes-process"> 
            <input type="hidden" name="listpoint" value="">
            <input type="hidden" name="name" value=''>
            <button type="button">Sauver <i class="fa-solid fa-download"></i></button>
        </form>
    <?php endif; ?>
    </div>

</div>

<div id="modal" class="modal">
  
    <div  class="modal-content">
        <span class="cross">
            <i class="fa-solid fa-circle-xmark"></i>
        </span>
        
        <fieldset>
            <legend>Route</legend>
            <input type="text" name="name" placeholder="Nommer cette route">
        </fieldset>
        
        <button><span>Valider</span><i class="fa-solid fa-circle-check"></i></button>
    </div>
 
</div>

<div id="map"></div>
<script src="script/map.js"></script>

