<?php
	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}
?>

<div id="sign-container">
    
    <form id="sign_profil" class="bgcolor-green" method='post' action='./profil-delete'>
        
        <fieldset class="bgcolor-blue">
            <legend class="bgcolor-red">Suppression</legend>
            
            <input class="bgcolor-white form-input" type="password" name="password" placeholder="mot de passe">
        </fieldset>
        
        <button class="delete-user-sure bgcolor-red hover-green" type="submit" ><span>Confirmer</span><i class="fa-solid fa-trash"></i></button>
    </form>
    


    <?php if(isset($error)): ?>
		<p class="error"><?= $error ?></p>
	<?php endif ?>
	
</div>
<a href='./profil'>Non</a>

<a href='./user-delete'>OUI</a>