<?php
	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}
?>

<div id="sign-container">
    
    <form class="sign-form" method='post' action='./profil-process'>
        
        <fieldset>
            <!--<?php var_dump($user_info);?>-->
            <legend>nom d'utilisateur : </legend>
            
            <input type="text" name="new_username" placeholder="<?= htmlspecialchars($_SESSION['user']->getUsername())?>">
            
        </fieldset>
    
        <fieldset>
            <legend>email : </legend>
            
            <input type="email" name="new_email" placeholder="<?= htmlspecialchars($_SESSION['user']->getEmail())?>">
            
        </fieldset>
    
        <fieldset>
            <legend>Mot de passe</legend>
            
            <input type="password" name="new_password" placeholder="nouveau mdp">
            <input type="password" name="new_password_confirm" placeholder="vérifier mdp">
            
        </fieldset>
        
        <button type="submit" >Mettre à jour</button>
    </form>
    
    <a class="delete-user" href="./profil-delete">Supprimer votre compte</a>

    <?php if(isset($error)): ?>
		<p class="error"><?= $error ?></p>
	<?php endif ?>
	
</div>
    
    
    
    
    
