<!--<?php var_dump($_POST);?>-->




<!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
    
<!--Script-->
    <script defer type="module" src="./script/module/Position.js"></script>
    <script defer type="module" src="./script/module/ListPoint.js"></script>

    <!--<script defer type="module" src="./script/map.js"></script>-->
    <script defer type="module" src="./script/routes.js"></script>
    <!--<script defer type="text/javascript" src="script/map.js"></script>-->

<div id='routes'>
        <ul>
            <?php foreach ($lists as $list):?>
              
            <li 
                data-name="<?=htmlspecialchars($list['name'])?>"
                data-uniqid="<?=htmlspecialchars($list['uniq_id'])?>"
                data-value="<?=htmlspecialchars($list['list_point'])?>"
            >
                
                <span class='label'><?=htmlspecialchars($list['name'])?></span>
                
                <span class="remove" data-index="" style="display: none;">
                    <i class="fa-solid fa-circle-xmark"></i>
                </span>
            </li>
              
            <?php endforeach;?>   
        </ul>
    <form method='post' action='./routes-process'>
        <input type="hidden" name="uniq_id_list_remove" value="">
    </form>
</div>

<div id="modal" class="modal">
  
    <div  class="modal-content">
        <span class="cross">
            <i class="fa-solid fa-circle-xmark"></i>
        </span>
        
        <fieldset>
            <legend>Attention</legend>
            <p></p>
        </fieldset>
        
        <button class='remove'>Supprimer</button>
    </div>
 
</div>

<div id="listpoint">


    <!--<div class="drag-bar"></div>-->


    <div class="position">
        <span>Votre position</span>
    </div>


    <ul>
        <!--list of point-->
    </ul>
    <template> <!--template of point-->
        <li class="point" draggable="true">
            
            <span class='label'>
                <!--label of point-->
            </span>
            
        </li>
    </template>

    <div class="total">
        <span>Total : 26km / 1h34</span>
        
    
        <form method="post" action="./"> 
            <input id="load_input"type="hidden" name="list_uniq_id" value="">
            
            <button type="button">Charger</button>
        </form>
    
    </div>


    
</div>

<div id="map"></div>
<script type="text/javascript" src="script/map.js"></script>

