<!-- Leaflet Script -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
    
<!--Script-->
    <script type="module" src="./script/module/Position.js"></script>
    <script type="module" src="./script/module/ListPoint.js"></script>
    <script type="module" src="./script/routes.js"></script>


<div id='routes'>
    <ul>
        <li 
            data-name="<?=htmlspecialchars($list['name'])?>"
            data-uniqid="<?=htmlspecialchars($list['uniq_id'])?>"
            data-value="<?=htmlspecialchars($list['listpoint'])?>"
        >
            <span class='label'><?=htmlspecialchars($list['name'])?></span>
        </li>
    </ul>
    <form id="remove_form" method='post' action='./routes-process'>
        <input type="hidden" name="uniq_id_list_remove" value="">
    </form>
    
</div>

<!--<div id="modal" class="modal">-->
  
<!--    <div  class="modal-content">-->
<!--        <span class="cross">-->
<!--            <i class="fa-solid fa-circle-xmark"></i>-->
<!--        </span>-->
        
<!--        <fieldset>-->
<!--            <legend>Attention</legend>-->
<!--            <span>Voulez-vous supprimer cette route ?</span>-->
<!--            <p></p>-->
<!--        </fieldset>-->
        
<!--        <button class='remove'><i class="fa-solid fa-trash"></i> Supprimer</button>-->
<!--    </div>-->
 
<!--</div>-->

<div id="listpoint">

    <!--<div class="drag-bar"></div>-->

    <div class="position">
        <span><i class="fa-solid fa-location-crosshairs"></i> Votre position</span>
    </div>

    <ul></ul><!--list of point-->

    <template> <!--template of point-->
        <li class="point">
            <div class="label-box">
                <span class='label'></span>
                
            </div>
        </li>
    </template>

    <div class="total">
        <span><i class="fa-solid fa-map-location-dot"></i><span class='label'></span></span>

        <form id="load_form" method="post" action="./home-process"> 
            <input id="load_input" type="hidden" name="list_uniq_id" value="">
            
            <button type="button"><i class="fa-solid fa-upload"></i> Charger</button>
        </form>
    </div>

</div>

<div id="map"></div>
<script src="script/map.js"></script>

