<?php

	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}

?>
<div id="sign-container">
    <form id="sign_up" class="bgcolor-green" method="post" action="./sign-forget">
        <fieldset class="bgcolor-blue">
            <legend class="bgcolor-red">Mot de passe oublié</legend>
            
            
            <input 
                class="bgcolor-white form-input" 
                type="email" name="email" placeholder="Adresse électronique" 
                <?= isset($_SESSION['formSignData']['email']) ? 
                    'value="'.$_SESSION['formSignData']['email'].'"' : null ?>
            required>
            
        </fieldset>
        <button class="bgcolor-yellow form-button hover-green" type="submit" ><span>Valider</span><i class="fa-solid fa-circle-check"></i></button>
    </form>

    <?php if(isset($error)): ?>
		<p class="error"><?= $error ?></p>
	<?php endif ?>
	
</div>