<?php

	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}
	if(array_key_exists('info', $_SESSION))
	{
		$info = $_SESSION['info'];
		unset($_SESSION['info']);
	}

?>
<div id="sign-container">
    <form id="sign_up" class="sign-form" method="post" action="./sign-up">
        <fieldset>
            <legend>Inscription</legend>
            
            <input type="text" name="username" placeholder="Pseudo" 
                <?= isset($_SESSION['formSignData']['username']) ?
                    'value="'.$_SESSION['formSignData']['username'].'"' : null ?>
            required>
            
            <input type="email" name="email" placeholder="Adresse électronique" 
                <?= isset($_SESSION['formSignData']['email']) ? 
                    'value="'.$_SESSION['formSignData']['email'].'"' : null ?>
            required>
            
            <input type="password" name="password" placeholder="Mot de passe" required>
            <input type="password" name="password_confirm" placeholder="Vérifier votre mdp" required>
            
        </fieldset>
        <button type="submit" ><span>Valider</span><i class="fa-solid fa-circle-check"></i></button>
    </form>

    <?php if(isset($error)): ?>
		<p class="error"><?= $error ?></p>
	<?php endif ?>
	
	<?php if(isset($info)): ?>
    	<p class="info"><?= $info ?></p>
    <?php endif ?>
	
</div>