<?php

	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}
	if(array_key_exists('info', $_SESSION))
	{
		$info = $_SESSION['info'];
		unset($_SESSION['info']);
	}

?>

<div id="sign-container">
    <form id="sign_in" class="bgcolor-green" method="post" action="./sign-in">
        <fieldset class="bgcolor-blue">
            <legend class="bgcolor-red">Connexion</legend>
            
            <input
                class="bgcolor-white form-input" 
                type="email" name="email" placeholder="Adresse électronique" 
                value="<?= isset($_SESSION['formSignData']['email']) ? 
                    $_SESSION['formSignData']['email'] : null ?>"
            required>
            
            <input 
                class="bgcolor-white form-input" 
                type="password" name="password" placeholder="Mot de passe"
            required>
            
        </fieldset>
        
        <button  class="bgcolor-yellow form-button hover-green" type="submit" >
            <span>Valider</span><i class="fa-solid fa-circle-check"></i>
        </button>
    </form>
    
    <a class="delete-user bgcolor-red hover-green" href="./sign-forget">
        <i class="fa-solid fa-arrows-rotate"></i><span>Mot de passe oublié</span>
    </a>
    
    <?php if(isset($error)): ?>
    	<p class="error"><?= $error ?></p>
    <?php endif ?>
    
    <?php if(isset($info)): ?>
    	<p class="info"><?= $info ?></p>
    <?php endif ?>
    
</div>
