<?php

	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}

?>


<form id="sign_in" class="sign-form" method="post" action="./sign-in">
    <fieldset>
        <legend>Connection</legend>
        
        <input type="email" name="email" placeholder="Adresse électronique" 
            <?= isset($_SESSION['formSignData']['email']) ? 
                'value="'.$_SESSION['formSignData']['email'].'"' : null ?>
        required>
        
        <input type="password" name="password" placeholder="Mot de passe" required>
        <input type="submit" value="Valider">
    </fieldset>
</form>

<?php if(isset($error)): ?>
	<p style="color: red;"><?= $error ?></p>
<?php endif ?>
