<?php

	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}

?>
<div id="sign-container">
    <form id="sign_up" class="sign-form" method="post" action="./sign-up">
        <fieldset>
            <legend>Inscription</legend>
            
            <input type="text" name="username" placeholder="Pseudo" 
                <?= isset($_SESSION['formSignData']['username']) ?
                    'value="'.$_SESSION['formSignData']['username'].'"' : null ?>
            required>
            
            <input type="email" name="email" placeholder="Adresse électronique" 
                <?= isset($_SESSION['formSignData']['email']) ? 
                    'value="'.$_SESSION['formSignData']['email'].'"' : null ?>
            required>
            
            <input type="password" name="password" placeholder="Mot de passe" required>
            <input type="password" name="password_confirm" placeholder="Vérifier votre mdp" required>
            
        </fieldset>
        <button type="submit" >Valider</button>
    </form>

    <?php if(isset($error)): ?>
		<p class="error"><?= $error ?></p>
	<?php endif ?>
	
</div>