<?php

	if(array_key_exists('error', $_SESSION))
	{
		$error = $_SESSION['error'];
		unset($_SESSION['error']);
	}

?>
<div id="sign-container">
    <form id="sign_up" class="bgcolor-green" method="post" action="./sign-forget">
        <fieldset class="bgcolor-blue">
            <legend class="bgcolor-red">
                <label for="email">Mot de passe oublié</label>
            </legend>
            
            <input id="email"
                class="bgcolor-white form-input" 
                title="Veuillez entrer votre adresse électronique" 
                placeholder="Adresse électronique"
                type="email" name="email"  
                value="<?= isset($_SESSION['formSignData']['email']) ? 
                   $_SESSION['formSignData']['email'] : null ?>"
            required>
        </fieldset>

        <button class="bgcolor-yellow form-button hover-green" type="submit" >
            <span>Valider</span><i class="fa-solid fa-circle-check"></i>
        </button>
    </form>

    <?php if(isset($error)): ?>
		<p class="error"><?= $error ?></p>
	<?php endif ?>
</div>