
    <form method="post" action="./sign-up">
        <fieldset>
            <legend>Inscription</legend>
            <input type="text" name="username" placeholder="Pseudo"/>
            <input type="email" name="email" placeholder="Adresse électronique"/>
            <br>
            <input type="password" name="password" placeholder="Mot de passe"/>
            <input type="password" name="password_confirm" placeholder="Vérifier votre mdp"/>
            <input type="submit" value="Soumettre"/>
        </fieldset>
    </form>
