<script type="module" src="./script/module/SearchBar.js"></script>

<div id="search_bar" class="bgcolor-gray border-none">
	<span id="search_box" class="bgcolor-white border-none">
		<span id="search_glass">
			<i class="fa-solid fa-magnifying-glass"></i>
		</span>

		<input id="search_input" class="form-input"type="text" name="search_adress" placeholder="recherche addresse">

		<span id="search_cross">
			<i class="fa-regular fa-circle-xmark"></i>
		</span> 
	</span>

	<ul id="search_results"></ul>
</div>