<script type="module" src="./script/module/SearchBar.js"></script>
<div id="searchbar" class="bgcolor-gray border-none">
	
	<span id="searchbar_input" class="bgcolor-white border-none">
		<span id="search_glass">
			<i class="fa-solid fa-magnifying-glass"></i>
		</span>
		<input id="search_input" class="form-input"type="text" name="search_adress" placeholder="recherche addresse">
		<span id="search_cross">
			<i class="fa-regular fa-circle-xmark"></i>
		</span> 
	</span>
	<ul id="searchbar_results"></ul>
</div>